### ISSUE TITLE
指令鸣潮数据运行报错

### ISSUE THREAD

**Issue by Baoer1** [ConcyWee/nonebot-plugin-kurogames#1]
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kurogames, lineno=31) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/__init__.py", line 80, in _
    pic_result = await mc_data_handler(data_row)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/handler/mc_handlers/mc_data_handler.py", line 48, in mc_data_handler
    data_pic = await mc_pic_render(mc_result)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/handler/mc_handlers/mc_pic_render.py", line 33, in mc_pic_render
    with open(mc_result_path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/Static/mcResult.html'

**Comment by ConcyWee** [comment]
看起来是因为代码中文件名和实际文件名大小写不一致而导致出现“未找到文件”的错误。

现在已发布新版代码，请等nonebot收到更新后更新插件版本至0.2.8。

如果更新后仍有问题，欢迎再次反馈~

**Comment by Baoer1** [comment]
已更新0.2.8，出现新的报错
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kurogames, lineno=31) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/__init__.py", line 80, in _
    pic_result = await mc_data_handler(data_row)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/handler/mc_handlers/mc_data_handler.py", line 48, in mc_data_handler
    data_pic = await mc_pic_render(mc_result)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/handler/mc_handlers/mc_pic_render.py", line 46, in mc_pic_render
    await page.goto(rendered_template_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8818, in goto
    await self._impl_obj.goto(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 524, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
Call log:
navigating to "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_kurogames/Static/Outputs/mc_rendered_template.html", waiting until "load"

**Comment by ConcyWee** [comment]
这可能是因为路径硬编码导致的Linux平台特有的问题，目前我自用的Windows环境没有这个问题

我重新发布了一版代码（0.2.9）来尝试修复这个问题，请等待nonebot收到更新后更新插件版本至0.2.9并再次尝试

更新后烦请告知运行结果~  这将对插件的开发有很大帮助~🫶

**Comment by Baoer1** [comment]
已更新0.2.9，正常运行无报错
