### ISSUE TITLE
鸣潮数据 指令报错

### ISSUE THREAD

**Issue by dokurorz** [ConcyWee/nonebot-plugin-kurogames#4]
发送`鸣潮数据`指令后，报错如下
```
Traceback (most recent call last):
  File "/root/python/my-bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot_plugin_kurogames/__init__.py", line 80, in _
    pic_result = await mc_data_handler(data_row)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot_plugin_kurogames/handler/mc_handlers/mc_data_handler.py", line 48, in mc_data_handler
    data_pic = await mc_pic_render(mc_result)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/nonebot_plugin_kurogames/handler/mc_handlers/mc_pic_render.py", line 36, in mc_pic_render
    rendered_html = template.render(data)
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/root/python/my-bot/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 256, in top-level template code
ZeroDivisionError: division by zero
```

账号登录是没问题的，`鸣潮抽卡数据`可以正常运行

**Comment by ConcyWee** [comment]
已调查出原因：由于库洛更新的数据格式，导致出现数字0作为除数从而产生报错。
正在修改相关代码和逻辑，请等待今晚插件版本更新~ 感谢支持~🫶

**Comment by ConcyWee** [comment]
@dokurorz 插件已更新，请等待nonebot商店获取到最新版本~
