### ISSUE TITLE
鸣潮数据相关全部报错，但是网络链接正常

### ISSUE THREAD

**Issue by WhyPilotXia** [ConcyWee/nonebot-plugin-kurogames#6]
使用“/库洛登录token”：
报错：错误: Expecting value: line 1 column 1 (char 0)
下面是鸣潮数据相关全部报错。使用手机号验证码可以登录但是只有签到功能看起来正常
09-09 23:01:49 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 896151622 from 2743218818@[群:683973033] '/鸣潮数据'
09-09 23:01:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kurogames, lineno=31)
09-09 23:01:51 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kurogames, lineno=31) running complete
09-09 23:01:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kurogames, lineno=31) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line
 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\__init__.py", line 82, in _
    pic_result = await mc_data_handler(data_row)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_data_handler.py", line 48, in mc_data_handler
    data_pic = await mc_pic_render(mc_result)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 56, in mc_pic_render
    result = await html_render(mc_result_path, rendered_template_path, data, 1920, 1080, '500')
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 9, in html_render
    rendered_html = template.render(data)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 380, in top-level template code
TypeError: 'NoneType' object is not iterable
09-09 23:02:09 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 2020206950 from 2743218818@[ 群:683973033] '/鸣潮探索数据'
09-09 23:02:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kurogames, lineno=35)
Task exception was never retrieved
future: <Task finished name='Task-2591' coro=<Connection.run() done, defined at C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
09-09 23:02:10 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kurogames, lineno=35) running complete
09-09 23:02:10 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kurogames, lineno=35) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line
 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\__init__.py", line 125, in _
    pic_result = await mc_explore_detail_handler(data_row)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_data_handler.py", line 61, in mc_explore_detail_handler
    data_pic            = await mc_explore_render(mc_explore_data['data'])
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 69, in mc_explore_render
    result = await html_render(mc_result_path, rendered_template_path, data, 1920, 1080, '500')
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 13, in html_render
    async with async_playwright() as p:
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
09-09 23:02:11 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 2136887501 from 1617379220@[ 群:764561089] '快给我发个口球带带'
09-09 23:02:12 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 816601422 from 2386877781@[群:667231990] '[image:file=30A0C8ED5E344A0FA5D9C3BE9D11FAB3.jpg,subType=1,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyMzg2...,file_size=9071]'
09-09 23:02:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.综合, lineno=38)
09-09 23:02:12 [INFO] nonebot | Matcher(type='message', module=src.plugins.综合, lineno=38) running complete
09-09 23:02:29 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1770182202 from 2386877781@[ 群:667231990] '希望库洛国庆多来点活动'
09-09 23:02:32 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1661322353 from 2635248576@[ 群:764561089] '?'
09-09 23:02:36 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 595981653 from 2386877781@[群:667231990] '不然产能又跟不上'
09-09 23:02:39 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1095974326 from 2386877781@[ 群:667231990] '[image:file=F6A51491DDD07AE15A4A4C07A86EE2B5.jpg,subType=7,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyMzg2...,file_size=8111]'
09-09 23:02:43 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 280278975 from 2743218818@[群:683973033] '/战双数据'
09-09 23:02:43 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kurogames, lineno=28)
09-09 23:02:44 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kurogames, lineno=28) running complete
09-09 23:03:08 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1736893639 from 592081700@[群:667231990] '我记得好像库洛的产能好像一直都不是很高了。'
09-09 23:03:09 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1062283092 from 2743218818@[ 群:683973033] '/鸣潮角色面板 秧秧'
09-09 23:03:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kurogames, lineno=36)
Task exception was never retrieved
future: <Task finished name='Task-6971' coro=<Connection.run() done, defined at C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
09-09 23:03:10 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kurogames, lineno=36) running complete
09-09 23:03:10 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kurogames, lineno=36) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line
 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\__init__.py", line 139, in _
    pic_result = await mc_role_detail_handler(data_row, role_name)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_data_handler.py", line 87, in mc_role_detail_handler
    data_pic = await mc_role_detail_render(role_detail['data'], user_data['data'])
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 105, in mc_role_detail_render
    result = await html_render(mc_result_path, rendered_template_path, data, 1920, 1080, '500')
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 13, in html_render
    async with async_playwright() as p:
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
09-09 23:03:24 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 636001050 from 1617379220@[群:764561089] '明明已经努力把自己表演的很逆天了'
09-09 23:03:28 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1647492817 from 2528149365@[ 群:764561089] '？'
09-09 23:03:28 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 684225090 from 1617379220@[群:764561089] '为什么没有人给我禁言'
09-09 23:03:36 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1030375234 from 2528149365@[ 群:764561089] '要给你颁个奖吗'
09-09 23:03:39 [SUCCESS] nonebot | OneBot V11 2124667541 | [message.group.normal]: Message 1353155754 from 2743218818@[ 群:683973033] '/鸣潮深渊数据'
09-09 23:03:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kurogames, lineno=37)
09-09 23:03:40 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kurogames, lineno=37) running complete
09-09 23:03:40 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kurogames, lineno=37) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line
 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\__init__.py", line 154, in _
    result = await mc_tower_detail_handler(data_row)
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_data_handler.py", line 103, in mc_tower_detail_handler
    data_pic = await mc_tower_render(tower_data['data'], user_data['data'])
  File "C:\Users\y1751\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kurogames\handler\mc_handlers\mc_pic_render.py", line 109, in mc_tower_render
    difficultyListLen = len(data['difficultyList'])
TypeError: object of type 'NoneType' has no len()

**Comment by ConcyWee** [comment]
看起来你并没有深渊的数据，暂时不清楚是哪里出的问题，方便加群说明下吗
https://qm.qq.com/q/qSclXekdH4

**Comment by WhyPilotXia** [comment]
好的，谢谢我加了



---Original---
From: ***@***.***&gt;
Sent at: 2024年9月9日(Mon) Evening11:15
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ConcyWee/nonebot-plugin-kurogames] 鸣潮数据相关全部报错，但是网络链接正常 (Issue #6)




 
看起来你并没有深渊的数据，暂时不清楚是哪里出的问题，方便加群说明下吗
 https://qm.qq.com/q/qSclXekdH4
